# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.network "public_network"
  config.vm.box = "chef/centos-7.0"
  config.vm.synced_folder "conf", "/tmp/conf"
  config.vm.provision :shell, path: "setup-server.sh"
end
